version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: text-classifier-api:latest
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    image: text-classifier-ui:latest
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
